### ISSUE TITLE
[Question] Book's publication and difference to the 1st edition

### ISSUE THREAD

**Issue by vfdev-5** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#1]
Hi @Shmuma, 
recently found this repository and very excited to read the book behind these examples. Can you please provide some details on book's publication planning and the difference with the 1st edition ?
Thanks

**Comment by Shmuma** [comment]
Hi!

Yep, 2nd edition is currently in progress (as you might see on commit history), it will have examples updated to pytorch 1.2 + ignite will be used to make them shorter. In terms of content, will have 6 new chapters and small reorganisations in the structure:
* chapter about ways to speed up RL methods using engineering tricks (ch09 here)
* chapter about TextWorld environment (ch15)
* chapter about RL in robotics (not yet written)
* chapter about advanced exploration techniques
* RL in discrete optimization problems using Rubic's cube as an example
* multi-agent setup
Also have plans to write about POMDP, but not sure about the timeline.

It is expected to be published in Nov-Dec this year. If you want to participate in "early review" program, when electronic copy is provided before the official publish, you can give me your mail here or send a note to max.lapan@gmail.com, I'll forward it to publisher.

**Comment by vfdev-5** [comment]
@Shmuma thanks for the information. Yes, I would be interested in this early review program. Here is my email vfdev.5@gmail.com

Concerning Ignite, if any of your coded classes/features would be intersting to put into contrib module, we can work on it too.

**Comment by Shmuma** [comment]
Ok, email recorded. Publisher normally gathers the list of contacts for early review before the release and will send a mail with download link.

In terms of ignite contribution, thanks for the offer. So far I've implemented those helper handlers: https://github.com/Shmuma/ptan/blob/master/ptan/ignite.py, but their functionality relies on ptan library, so, I think it would be better to keep them in ptan.
