### ISSUE TITLE
Chapter03/04_atari_gan_ignite - Loss values order is wrong

### ISSUE THREAD

**Issue by NilsGu** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#10]
Hello,

it seems the loss values are logged with a wrong name. RunningAverage binds to the wrong values.
Here out[0] should be avg_loss_dis and so out[1] should be avg_loss_gen:
https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/4915540ca592a5a6d88f8cb63eff2c2ebf57bb06/Chapter03/04_atari_gan_ignite.py#L193-L196

The order here is dis_loss first:
https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/4915540ca592a5a6d88f8cb63eff2c2ebf57bb06/Chapter03/04_atari_gan_ignite.py#L188

**Comment by Shmuma** [comment]
Hi!

You're right. Thanks for the report! Fixed with https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/commit/6e66af7f108b29aa192620ef0fc6895f74d851a5
