### ISSUE TITLE
Reason for adding CNNs together in chapter 23?

### ISSUE THREAD

**Issue by NikEyX** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#13]
Hi Max,

I own the first edition of your book, so maybe it's explained in the second version, but since I couldn't find an explanation I was wondering why you are calculating conv nets on the residuals (in chapter 23: `lib/model.py`)?

```
        v = self.conv_in(x)
        v = v + self.conv_1(v)
        v = v + self.conv_2(v)
        v = v + self.conv_3(v)
        v = v + self.conv_4(v)
        v = v + self.conv_5(v)
        ......
```

Why exactly is this done? To what extent do the residuals between conv nets add value? Does this significantly increase performance vs a single CNN with more features? Asking, because it takes a ton of time to run.

Thanks!

**Comment by Shmuma** [comment]
Hi!

They are not just added together, they form a residual connections and they're mentioned in the original paper. 

In the paper (page 357) they say:

> Using a residual network was more accurate, achieved lower error and improved performance in AlphaGo by over 600 Elo.

But I haven't done comparison how it influences connect4 implementation.
