### ISSUE TITLE
Chapter 3 - 03_atari_gan: Normalization problem

### ISSUE THREAD

**Issue by tarod13** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#15]
The image normalization in the batch iterator (iterate_batches) is not correct. Instead of 

`batch_np *= 2.0 / 255.0 - 1.0`,

it should be 

`batch_np = 2.0 * batch_np / 255.0 - 1.0`.

**Comment by Shmuma** [comment]
Yes, good point. Fixed in both master and `torch-1.7` branches.
