### ISSUE TITLE
When I run train_model_conv(Chapter 10) in google colab I recieve an error

### ISSUE THREAD

**Issue by AndreyStille** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#16]
ValueError: Argument `epoch_length` should be defined if `data` is an iterator
![2](https://user-images.githubusercontent.com/65295663/81823657-30a6c180-953d-11ea-88c4-d5a1815977f7.PNG)
![1](https://user-images.githubusercontent.com/65295663/81823660-313f5800-953d-11ea-9db8-b711bd73494d.PNG)

**Comment by vfdev-5** [comment]
@AndreyStille please install `pytorch-ignite==0.2.1` version as required in https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/master/requirements.txt or set `epoch_length` to any valid epoch length.

**Comment by AndreyStille** [comment]
Thanks for so quick answer
