### ISSUE TITLE
Chapter 10 (Error(s) in loading state_dict for DQNConv1D) error when try to launch run_model.py

### ISSUE THREAD

**Issue by AndreyStille** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#17]
![1](https://user-images.githubusercontent.com/65295663/81928144-7de26c00-95ed-11ea-96e7-5b6962e19910.PNG)
![2](https://user-images.githubusercontent.com/65295663/81928147-7f139900-95ed-11ea-9dee-476855c0c67d.PNG)

RuntimeError: Error(s) in loading state_dict for DQNConv1D:
	size mismatch for fc_val.0.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 5376]).
	size mismatch for fc_adv.0.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 5376]).

**Comment by Shmuma** [comment]
Please check that the model you're loading was trained with the same command line arguments. From your error, it looks like you're trying to load model trained without `--conv` option into convolution network.

**Comment by AndreyStille** [comment]
![3](https://user-images.githubusercontent.com/65295663/81938896-429c6900-95fe-11ea-804b-0a996e7f17c9.PNG)
here is training code

**Comment by AndreyStille** [comment]
Или там еще кроме создания экземпляра модели, нужно было указать что это Conv.?

**Comment by Shmuma** [comment]
На структуру модели еще влияет среда. Я бы посоветовал сделать `print(net)` в коде обучения и в коде где грузится модель (перед загрузкой весов из файла) и сравнил бы результат. Скорее всего отличаются параметры где-то

**Comment by AndreyStille** [comment]
Извините что отнимаю ваше время, но очень хочется разобраться
Действительно модели отличаются
Но ведь в обоих запусках модели задаются абсолютно одинаково, как экземпляр одного и того же класса, c одинаковыми аргументами, не понимаю в чем может быть проблема

![Net_crating_while_model_run](https://user-images.githubusercontent.com/65295663/81969709-12b58b80-9627-11ea-9a70-bcfbcaba96a1.PNG)
![Net_creating_while_training](https://user-images.githubusercontent.com/65295663/81969711-13e6b880-9627-11ea-9bcc-056323a0a0ef.PNG)


![DQNConv_when_run_model](https://user-images.githubusercontent.com/65295663/81969451-ad619a80-9626-11ea-802a-d5d2c4b8a245.PNG)
![DQNConv_when_train_model_conv](https://user-images.githubusercontent.com/65295663/81969455-adfa3100-9626-11ea-919b-28fe2ef61901.PNG)

**Comment by AndreyStille** [comment]
если явно в run_model.py задаю размеры создаваемой модели, то вылазит такая ошибка:
![when_run](https://user-images.githubusercontent.com/65295663/81971707-2d3d3400-962a-11ea-8421-4a3bd1492a23.PNG)

**Comment by Shmuma** [comment]
Так, размер на входе в полносвязный слой зависит от всего `env.observation_space.shape`.

Попробуйте добавить `print(env.observation_space.shape)` перед уже добавленными print-ами, что там будет?

Как-то неправильно модель среды создается.

**Comment by Shmuma** [comment]
Мне кажется, это значение параметра `--bars`, передаваемое в `run_model.py` отличается от параметра, с которым училась модель. В общем, нужно добиться того, чтобы наблюдения из среды при запуске модели совпадали с наблюдениями из среды при обучении, без этого ничего работать все равно не будет :)

Ошибка "Input type should be the same" вызвана тем, что входные данные находятся в GPU а модель на CPU (или наоборот). В общем, где-то забыто `.to(device)`

**Comment by AndreyStille** [comment]
Да
все так очевидно
я тренировал модель на 10 свечах, а запускал с 50 
почему-то думал что в train_model_conv априори стоит 50 баров
Большое спасибо за помощь и за отличную книгу
