### ISSUE TITLE
Chapter 3 - 03/04_atari_gan - incorrectly ported from the first edition

### ISSUE THREAD

**Issue by genijmath** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#20]
In addition to [issue 15](https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/issues/15), `gen_input_v` initialization is corrupted:

written:
```
        gen_input_v.normal_(0, 1)
```
should be:
```
        gen_input_v = gen_input_v.normal_(0, 1)
```

As a side note, I find the following implementation more readable: 
```
        gen_input_v = (
            torch.FloatTensor(BATCH_SIZE, LATENT_VECTOR_SIZE, 1, 1)
                .normal_(0, 1)
                .to(device))
```
(just add extra parenthesis around to continue on the next line).

**Comment by Shmuma** [comment]
PyTorch has a convention that underscores in function names indicate that function mutates the object. So, extra assignment is not needed:
```
>>> t = torch.zeros(2, 3)
>>> t
tensor([[0., 0., 0.],
        [0., 0., 0.]])
>>> t.normal_()
tensor([[-0.1766, -0.8160, -1.7392],
        [-0.4458, -1.3190, -0.0916]])
>>> t
tensor([[-0.1766, -0.8160, -1.7392],
        [-0.4458, -1.3190, -0.0916]])
```
