### ISSUE TITLE
Very well written book, but PTAN is not worth.

### ISSUE THREAD

**Issue by saahiluppal** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#26]
Following your book, nicely explained concepts.

However PTAN i heavily used in demonstrations, but PTAN's experience.py is not readable, which is the main script of this library.

**Comment by Shmuma** [comment]
In general, agree. This module was nice and simple before OpenAI universe environments support was added. Then it become a mess :).
