### ISSUE TITLE
Wrappers changed for (CH 6 ) DQN solution 

### ISSUE THREAD

**Issue by billyg88** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#28]
The wrappers in the baselines repo have been changed from those presented on CH6.

(https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py)

I tried to use the ones defined in ale_wrappers, but unfortunately I could not get the DQN to converge. 
As soon as i changed to the newer ones, I was able to achieve convergence.

**Comment by Shmuma** [comment]
As far as I can see, openai baselines wrappers were updated more than a year ago, which means, examples' wrappers should be in sync. They are not 100% the same, as small pytorch-related adoptation is needed. 

That's strange that you cannot make DQN to converge. Are you sure you're using the same versions of components listed in requirements.txt? Version difference in gym might lead to wrong results, as actions and/or observations might change.
