### ISSUE TITLE
Unable to Install PTAN

### ISSUE THREAD

**Issue by general-rishkin** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#32]
I've just started reading your book and it reads really well. I've finished Chapter 2 and trying to install the prerequisites.
Everything is installed except PTAN where I get this error:

`Downloading install-1.3.4-py3-none-any.whl (3.1 kB)`
`ERROR: Could not find a version that satisfies the requirement torch==1.3.0 (from ptan==0.6) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0)
ERROR: No matching distribution found for torch==1.3.0 (from ptan==0.6)
`

Could you possibly upgrade the requirements?

**Comment by Shmuma** [comment]
Hi! At the moment, updating the requirements are tricky (but planned). You
can fulfill the requirements by installing pytorch first using conda
install and then install plan.

пн, 9 нояб. 2020 г., 21:22 general-rishkin <notifications@github.com>:

**Comment by missinglpf** [comment]
I also have this problem. How to solve it?

**Comment by Shmuma** [comment]
Please install 1.3.0 pytorch using conda with `conda install pytorch==1.3.0 torchvision cudatoolkit=10.1 -c pytorch` and then try to install ptan again.

Sorry for inconvenience, this will be resolved eventually

**Comment by general-rishkin** [comment]
Many thanks, will do.

Gennadiy
