### ISSUE TITLE
Chapter 4 - 01 cartpole.py: ValueError: probabilities do not sum to 1

### ISSUE THREAD

**Issue by bezineb5** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#35]
Hi,

While trying the cartpole example in the cross-entropy chapter, I came across that issue in the code:

```
Traceback (most recent call last):
  File "frombook.py", line 91, in <module>
    env, net, BATCH_SIZE)):
  File "frombook.py", line 44, in iterate_batches
    action = np.random.choice(len(act_probs), p=act_probs)
  File "mtrand.pyx", line 932, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

I tried to normalize probabilities:
```
        act_probs -= np.min(act_probs)
        act_probs /= np.sum(act_probs)
```

However, the probabilities are then just [1. 0.] or [0. 1.], it then fails with such error:
```
Traceback (most recent call last):
  File "cartpole_crossentropy.py", line 109, in <module>
    for iter_no, batch in enumerate(iterate_batches(env, net, BATCH_SIZE, device)):
  File "cartpole_crossentropy.py", line 48, in iterate_batches
    action = rng.choice(len(act_probs), p=act_probs)
  File "_generator.pyx", line 644, in numpy.random._generator.Generator.choice
ValueError: probabilities contain NaN
```

Could it be an initialization error?

FYI, I'm using:
torch==1.7.0
numpy==1.19.4

Thanks!

**Comment by Shmuma** [comment]
Interesting. I'm currently working on porting examples to torch 1.7, but this example worked for me. 

Is the error consistent (so, you're getting this error every time you run the example)?
This error means some of values produced by NN are too large, which might happen when something really bad happened with the training process (i.e. optimisation has diverged), but I've never seen this in this example - it normally just converge very quickly.

So, if this is something happened once - just ignore this :)

**Comment by sarvesh-packt** [comment]
Hi @bezineb5 ,

Please reopen if the issue still persists.

Thanks,

**Comment by sarvesh-packt** [comment]
Hi @bezineb5 ,

Please reopen if the issue still persists.

Thanks,
