### ISSUE TITLE
system requirements not stated

### ISSUE THREAD

**Issue by rfernand2** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#4]
Please state in the README.md:
   - which platforms are supported (are they Linux, Windows, and Mac?)
   - which versions of python are supported

**Comment by Shmuma** [comment]
The OS and python requirements are given in chapter 2 of the book. 

I have written and debugged examples on Linux (Ubuntu), also tested some of them on MacOSX. Windows wasn't tested, but could work, as PyTorch and Gym are currently supporting it. But that's not guaranteed.

In terms of python, 3.7 was used.
