### ISSUE TITLE
Errors during install on Windows

### ISSUE THREAD

**Issue by rfernand2** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#5]
I tried to install on Windows with a new conda virtual env with python=3.6, using:
   `pip install -r requirements.txt`

The following error resulted:

> ERROR: Could not find a version that satisfies the requirement torch==1.3.0 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
> ERROR: No matching distribution found for torch==1.3.0 (from -r requirements.txt (line 6))

However, if I pre-installed pytorch 1.3 using:
`conda install pytorch==1.3.0 torchvision cudatoolkit=10.1 -c pytorch `  
and then pip installed with the --user option: `pip install --user -r requirements.txt`, the install was successful.

FYI, on linux, the `pip install -r requirements.txt` worked correctly (the pre-install of pytorch and the --user option was not needed).

**Comment by Shmuma** [comment]
Yes, it might happen, I haven't tested the code on windows. You should also use python 3.7 instead of 3.6
