### ISSUE TITLE
[Error] not run on gpu chap3

### ISSUE THREAD

**Issue by pykeras** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#7]
https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/3855b2fa8b325b8039913fc42a6f6d3bffb3066c/Chapter03/03_atari_gan.py#L176
__*PyTorch __version__ : '1.4.0'*__

This will solve the error:
`gen_output_v = net_gener(gen_input_v.to(device)).to(device)`

**Comment by Shmuma** [comment]
Really puzzled how this issue appeared and passed my tests on gpu. Fixed with this commit: https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/commit/cb5a3d48b986c249cac22b0deaca1851fba4a7f7
