### ISSUE TITLE
Chapter08 - engine.run throw error when the input data is an iterator

### ISSUE THREAD

**Issue by naseeihity** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition#8]
https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/4915540ca592a5a6d88f8cb63eff2c2ebf57bb06/Chapter08/01_dqn_basic.py#L63

> ValueError: Argument `epoch_length` should be defined if `data` is an iterator

It seems that both `epoch_length` and `max_epochs` should be defined.  According to other issues, This seems to be due to the version of the `pytorch-ignite` I installed does not match the requirements.

However, i am not sure how much should I assign to these two parameters? As for now, i just assign a really big number to `max_epochs` and `batch_size` to `epoch_length`.

**Comment by vfdev-5** [comment]
@naseeihity please install pytorch-ignite according to the [requirements](https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition/blob/master/requirements.txt): v0.2.1
